name: Run Balle Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # این دکمه باعث می‌شود دستی هم بتوانی ربات را اجرا کنی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd708027c5415774a34b295f795764d858348d

      - name: Set up Python
        uses: actions/setup-python@0b93645e5efa73550a3b04c81f687498c4746014
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install telethon # یا هر کتابخانه‌ای که استفاده می‌کنی

      - name: Run Bot
        run: python main.py # اسم فایل اصلی رباتت
        
