name: Run Bale Bot on Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        # استفاده از SHA معتبر برای نسخه v4
        uses: actions/checkout@ac593985898399a8db84d7eaadac97312121c44d

      - name: Set up Python
        # استفاده از SHA معتبر برای نسخه v5
        uses: actions/setup-python@12359a6d33ed447db118330c50d2540843d04590
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python main.py
        
